apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: openmetadata-dependencies-dags
  labels:
    app: airflow
spec:
  accessModes:
    - ReadWriteOnce  # Longhorn supports ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
