airflow:
  enabled: true
  airflow:
    image:
      repository: docker.getcollate.io/openmetadata/ingestion
      tag: 1.5.7
      pullPolicy: "IfNotPresent"
    executor: "KubernetesExecutor"
    config:
      AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.session,airflow.api.auth.backend.basic_auth"
    users:
    - username: admin
      password: admin
      role: Admin
      email: spiderman@superhero.org
      firstName: Peter
      lastName: Parker
  web:
    service:
      type: LoadBalancer  # Expose Airflow web server via a load balancer for HA
    extraVolumes:
    - name: pod-template
      configMap:
        name: openmetadata-pod-template
        defaultMode: 420
    extraVolumeMounts:
      - name: pod-template
        readOnly: true
        subPath: pod_template.yaml
        mountPath: /opt/airflow/pod_templates/pod_template.yaml
  workers:
    enabled: false  # Disable workers for KubernetesExecutor
  flower:
    enabled: false  # Disable flower
  redis:
    enabled: false  # Disable redis for KubernetesExecutor
  externalDatabase:
    type: mysql
    host: mysql
    port: 3306
    database: airflow_db
    user: airflow_user
    passwordSecret: airflow-mysql-secrets
    passwordSecretKey: airflow-mysql-password
  dags:
    persistence:
      enabled: true
      storageClass: "gp2"  # Adjust the storage class
      accessMode: ReadWriteMany
      size: 2Gi
  logs:
    persistence:
      enabled: true
      storageClass: "gp2"
      accessMode: ReadWriteMany
      size: 2Gi
